-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Omistaja CASCADE;
DROP TABLE IF EXISTS Kampanja CASCADE;
DROP TABLE IF EXISTS Ryhma CASCADE;
DROP TABLE IF EXISTS Hahmoluokka CASCADE;
DROP TABLE IF EXISTS Hahmo CASCADE;
DROP TABLE IF EXISTS CampaignAchievements CASCADE;
DROP TABLE IF EXISTS K_saavutus CASCADE;
DROP TABLE IF EXISTS KampanjanSaavutus CASCADE;
DROP TABLE IF EXISTS R_saavutus CASCADE;
DROP TABLE IF EXISTS RyhmanSaavutus CASCADE;
DROP TABLE IF EXISTS Skenaario CASCADE;
DROP TABLE IF EXISTS Historia CASCADE;

