-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Omistaja CASCADE;
DROP TABLE IF EXISTS Kampanja CASCADE;
DROP TABLE IF EXISTS Ryhma CASCADE;
DROP TABLE IF EXISTS Hahmo CASCADE;
DROP TABLE IF EXISTS Historia CASCADE;
DROP TABLE IF EXISTS Hahmoluokka CASCADE;